import { Property, PropertyStatus, PropertyType } from "@/types";


export const COLORS = {
  NAVY: "#0F2540",
  TEAL: "#008C99",
  MUSTARD: "#FCC02E",
  RED: "#D63528",
  WHITE: "#FFFFFF",
  GRAY: "#F3F4F6",
};

export const DUMMY_PROPERTIES: Property[] = [
  {
    id: "godrej-1",
    title: "Godrej Orchard Estate",
    location: "Besa-Ghogli Road",
    city: "Nagpur",
    price: 4500000,
    priceDisplay: "₹45 L",
    bhk: "NA",
    area: 1200,
    areaUnit: "Sq. Ft.",
    imageUrl: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    ],
    statuses: [
      PropertyStatus.VERIFIED,
      PropertyStatus.RERA_REGISTERED,
      PropertyStatus.NEW_LAUNCH,
    ],
    type: PropertyType.BUY,
    category: "Plot",
    description:
      "A prestigious plotted development by Godrej Properties. Featuring world-class infrastructure, thematic gardens, and an elite clubhouse. Designed for high-appreciation and premium living.",
    amenities: [
      "Clubhouse",
      "Thematic Gardens",
      "24/7 Security",
      "Underground Utilities",
      "Jogging Track",
    ],
    growthScore: 9.7,
    proximity: {
      metro: "15 mins from Khapri Metro",
      highway: "Direct connectivity to Outer Ring Road",
      landmark: "Near Ghogli Square",
    },
  },
  {
    id: "marina-1",
    title: "Nagpur Marina Waterfront",
    location: "MIHAN / Wardha Road",
    city: "Nagpur",
    price: 22500000,
    priceDisplay: "₹2.25 Cr",
    bhk: 4,
    area: 3200,
    areaUnit: "Sq. Ft.",
    imageUrl: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    ],
    statuses: [PropertyStatus.VERIFIED, PropertyStatus.NEW_LAUNCH],
    type: PropertyType.BUY,
    category: "Villa",
    description:
      "Ultra-luxury waterfront villas inspired by international marina living. High ceilings, private elevators, and a deck overlooking the serene landscape of MIHAN.",
    amenities: [
      "Waterfront Deck",
      "Private Pool",
      "Home Automation",
      "Concierge Service",
      "Gym",
    ],
    growthScore: 9.1,
    proximity: {
      metro: "2km from MIHAN Metro",
      highway: "3 mins from NH-44",
      landmark: "Opposite AIIMS Nagpur",
    },
  },
  {
    id: "lok8-1",
    title: "Lok8 Business Hub",
    location: "Wardha Road",
    city: "Nagpur",
    price: 7500000,
    priceDisplay: "₹75 L",
    bhk: "NA",
    area: 850,
    areaUnit: "Sq. Ft.",
    imageUrl: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    ],
    statuses: [PropertyStatus.VERIFIED, PropertyStatus.RERA_REGISTERED],
    type: PropertyType.COMMERCIAL,
    category: "Commercial Space",
    description:
      "The new pulse of Nagpur business. Modern office spaces with high visibility on Main Wardha Road. Perfect for startups, corporate offices, and professional consulting firms.",
    amenities: [
      "High-speed Elevators",
      "Double-height Lobby",
      "Ample Parking",
      "Power Backup",
      "Security",
    ],
    growthScore: 8.9,
    proximity: {
      metro: "Walkable from Airport Metro",
      highway: "Zero Mile Connectivity",
      landmark: "Next to Lokmat Square",
    },
  },
  {
    id: "karamchand-1",
    title: "Karamchand Green Layout",
    location: "Besa-Pipla",
    city: "Nagpur",
    price: 3500000,
    priceDisplay: "₹35 L",
    bhk: "NA",
    area: 1100,
    areaUnit: "Sq. Ft.",
    imageUrl: [
      "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    ],
    statuses: [PropertyStatus.VERIFIED, PropertyStatus.RERA_REGISTERED],
    type: PropertyType.BUY,
    category: "Plot",
    description:
      "Eco-friendly plotted community focused on sustainable living. Wide internal cement roads, extensive plantation, and NMRDA sanctioned with RL.",
    amenities: [
      "Green Plantation",
      "Cement Roads",
      "Street Lights",
      "Water Connection",
      "Children Play Area",
    ],
    growthScore: 9.4,
    proximity: {
      highway: "5 mins to Outer Ring Road",
      landmark: "Near Besa Square",
      metro: "7km from Khapri Metro",
    },
  },
  {
    id: "kalptaru-1",
    title: "Kalptaru Exotica Residences",
    location: "Dharampeth Extension",
    city: "Nagpur",
    price: 13500000,
    priceDisplay: "₹1.35 Cr",
    bhk: 3,
    area: 1950,
    areaUnit: "Sq. Ft.",
    imageUrl: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    ],
    statuses: [PropertyStatus.VERIFIED, PropertyStatus.MOVE_IN_READY],
    type: PropertyType.BUY,
    category: "Flat",
    description:
      "Exotic living at its best. Spacious 3BHK apartments with 3-side open views and large balconies. Premium finishes and elite neighborhood in West Nagpur.",
    amenities: [
      "Sky Lounge",
      "Video Door Phone",
      "Modular Kitchen",
      "Fitness Center",
      "Solar Water Heating",
    ],
    growthScore: 8.2,
    proximity: {
      landmark: "5 mins from Zero Mile",
      metro: "Shankar Nagar Metro (1km)",
      highway: "Amravati Road Connectivity",
    },
  },
  {
    id: "1",
    title: "Shiv Heritage Apartments",
    location: "Dharampeth",
    city: "Nagpur",
    price: 18500000,
    priceDisplay: "₹1.85 Cr",
    bhk: 3,
    area: 1750,
    areaUnit: "Sq. Ft.",
    imageUrl: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    ],
    statuses: [PropertyStatus.VERIFIED, PropertyStatus.MOVE_IN_READY],
    type: PropertyType.BUY,
    category: "Flat",
    description:
      "A premium luxury apartment located in the heart of Dharampeth. Features Italian marble flooring, high-end modular kitchen, and private balconies overlooking the city skyline.",
    amenities: [
      "24/7 Security",
      "Gym",
      "Swimming Pool",
      "CCTV",
      "Power Backup",
      "Covered Parking",
    ],
    growthScore: 8.4,
    proximity: {
      metro: "500m from Dharampeth Metro",
      landmark: "Near Coffee House",
    },
  },
  {
    id: "2",
    title: "Orange City Smart Plot",
    location: "Wardha Road",
    city: "Nagpur",
    price: 4200000,
    priceDisplay: "₹42 L",
    bhk: "NA",
    area: 1500,
    areaUnit: "Sq. Ft.",
    imageUrl: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    ],
    statuses: [PropertyStatus.RERA_REGISTERED, PropertyStatus.NEW_LAUNCH],
    type: PropertyType.BUY,
    category: "Plot",
    description:
      "Fully developed NIT sanctioned plot in a gated community. Ready for immediate construction. Excellent appreciation potential due to proximity to the airport.",
    amenities: [
      "Walled Colony",
      "Underground Drainage",
      "Street Lights",
      "Cement Roads",
      "Gated Entry",
    ],
    growthScore: 9.6,
    proximity: {
      highway: "Direct Access to NH 44",
      landmark: "3 mins from Airport",
    },
  },
  {
    id: "3",
    title: "Hingna MIDC Resale Plot",
    location: "Hingna",
    city: "Nagpur",
    price: 2800000,
    priceDisplay: "₹28 L",
    bhk: "NA",
    area: 1200,
    areaUnit: "Sq. Ft.",
    imageUrl: [
      "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    ],
    statuses: [PropertyStatus.VERIFIED],
    type: PropertyType.BUY,
    category: "Plot",
    description:
      "Strategically located plot near Hingna MIDC. Ideal for residential or small-scale commercial use. Clear title and NMRDA sanctioned.",
    amenities: [
      "Near Highway",
      "Public Transport Access",
      "Electricity Connection",
    ],
    growthScore: 7.8,
    proximity: {
      metro: "2km from Hingna Metro",
      landmark: "Near ICICI Bank",
    },
  },
  {
    id: "4",
    title: "MIHAN IT Park Commercial",
    location: "MIHAN",
    city: "Nagpur",
    price: 45000000,
    priceDisplay: "₹4.5 Cr",
    bhk: "NA",
    area: 5000,
    areaUnit: "Sq. Ft.",
    imageUrl: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    ],
    statuses: [PropertyStatus.VERIFIED],
    type: PropertyType.COMMERCIAL,
    category: "Commercial Space",
    description:
      "High-grade commercial floor space ready for IT/ITES occupancy. Located within the special economic zone with modern glass facade and central air conditioning.",
    amenities: [
      "Fiber Optic Connectivity",
      "Multi-level Parking",
      "Cafeteria",
      "Conference Rooms",
    ],
    growthScore: 9.2,
    proximity: {
      landmark: "Opposite Infosys Hub",
      highway: "NH 44 Connectivity",
    },
  },
];
